name: SPFx DEV CI/CD

on:
  push:
    branches:
      - Dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build SPFx solution
        run: npx gulp bundle

      - name: Package SPFx solution
        run: npx gulp package-solution --ship

      - name: Upload SPFx package
        uses: actions/upload-artifact@v4
        with:
          name: user-access-management-dev
          path: solution/user-access-management.sppkg


